# Default values for service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry-797ecf26-f6b5-4fad-9e7a-d87a2b96853e.dyn.mayope.net/hello
  pullPolicy: Always
  version: latest

service:
  type: ClusterIP
  port: 80
  healthCheckPath: /


ingress:
  enabled: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
