apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/clusterissuer: "letsencrypt-prod"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "service.fullname" . }}
              servicePort: 80
