apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - hello.mayope.net
      secretName: docs-tls-secret
  rules:
    - host: hello.mayope.net
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "service.fullname" . }}
              servicePort: 80
